#!/bin/bash


[Unit]
Description = Backend Service

[Service]
User=expense
Environment=DB_HOST="db.ramadevops78s.store"
ExecStart=/bin/node /app/index.js
SyslogIdentifier=backend

[Install]
WantedBy=multi-user.target


##  hostingerlink  :  https://us-east-1.console.aws.amazon.com/route53/v2/hostedzones?region=us-east-1#/ListRecordSets/Z09642591E20MVGEA8NO6

#http://ramadevops78s.store/